// ─────────────────────────────────────────────────────────────────
// Scraper Constants — Known universities, cities, regex databases
// ─────────────────────────────────────────────────────────────────

/** Known German university hostname → canonical name + city mapping */
export const KNOWN_UNIVERSITIES: Record<string, { name: string; city: string }> = {
  'tum.de':              { name: 'Technical University of Munich', city: 'Munich' },
  'tu-berlin.de':        { name: 'Technische Universität Berlin', city: 'Berlin' },
  'tu-darmstadt.de':     { name: 'Technische Universität Darmstadt', city: 'Darmstadt' },
  'tu-dresden.de':       { name: 'Technische Universität Dresden', city: 'Dresden' },
  'tu-braunschweig.de':  { name: 'Technische Universität Braunschweig', city: 'Braunschweig' },
  'lmu.de':              { name: 'Ludwig-Maximilians-Universität München', city: 'Munich' },
  'fu-berlin.de':        { name: 'Freie Universität Berlin', city: 'Berlin' },
  'hu-berlin.de':        { name: 'Humboldt-Universität zu Berlin', city: 'Berlin' },
  'uni-heidelberg.de':   { name: 'Universität Heidelberg', city: 'Heidelberg' },
  'uni-freiburg.de':     { name: 'Universität Freiburg', city: 'Freiburg' },
  'uni-muenchen.de':     { name: 'Ludwig-Maximilians-Universität München', city: 'Munich' },
  'uni-bonn.de':         { name: 'Universität Bonn', city: 'Bonn' },
  'uni-koeln.de':        { name: 'Universität zu Köln', city: 'Cologne' },
  'uni-hamburg.de':      { name: 'Universität Hamburg', city: 'Hamburg' },
  'uni-goettingen.de':   { name: 'Georg-August-Universität Göttingen', city: 'Göttingen' },
  'uni-tuebingen.de':    { name: 'Universität Tübingen', city: 'Tübingen' },
  'uni-mannheim.de':     { name: 'Universität Mannheim', city: 'Mannheim' },
  'uni-muenster.de':     { name: 'Universität Münster', city: 'Münster' },
  'uni-stuttgart.de':    { name: 'Universität Stuttgart', city: 'Stuttgart' },
  'uni-erlangen.de':     { name: 'Friedrich-Alexander-Universität Erlangen-Nürnberg', city: 'Erlangen' },
  'fau.de':              { name: 'Friedrich-Alexander-Universität Erlangen-Nürnberg', city: 'Erlangen' },
  'kit.edu':             { name: 'Karlsruhe Institute of Technology', city: 'Karlsruhe' },
  'rwth-aachen.de':      { name: 'RWTH Aachen University', city: 'Aachen' },
  'uni-frankfurt.de':    { name: 'Goethe-Universität Frankfurt', city: 'Frankfurt' },
  'uni-jena.de':         { name: 'Friedrich-Schiller-Universität Jena', city: 'Jena' },
  'uni-wuerzburg.de':    { name: 'Julius-Maximilians-Universität Würzburg', city: 'Würzburg' },
  'uni-potsdam.de':      { name: 'Universität Potsdam', city: 'Potsdam' },
  'uni-augsburg.de':     { name: 'Universität Augsburg', city: 'Augsburg' },
  'uni-bayreuth.de':     { name: 'Universität Bayreuth', city: 'Bayreuth' },
  'uni-leipzig.de':      { name: 'Universität Leipzig', city: 'Leipzig' },
  'uni-konstanz.de':     { name: 'Universität Konstanz', city: 'Constance' },
  'uni-saarland.de':     { name: 'Universität des Saarlandes', city: 'Saarbrücken' },
  'uni-hannover.de':     { name: 'Leibniz Universität Hannover', city: 'Hannover' },
  'tu-clausthal.de':     { name: 'TU Clausthal', city: 'Clausthal-Zellerfeld' },
  'tu-chemnitz.de':      { name: 'Technische Universität Chemnitz', city: 'Chemnitz' },
  'tu-ilmenau.de':       { name: 'Technische Universität Ilmenau', city: 'Ilmenau' },
  'tu-kaiserslautern.de': { name: 'TU Kaiserslautern', city: 'Kaiserslautern' },
  'rptu.de':             { name: 'RPTU Kaiserslautern-Landau', city: 'Kaiserslautern' },
  'hs-mannheim.de':      { name: 'Hochschule Mannheim', city: 'Mannheim' },
  'uni-wuppertal.de':    { name: 'Bergische Universität Wuppertal', city: 'Wuppertal' },
  'uni-due.de':          { name: 'Universität Duisburg-Essen', city: 'Essen' },
  'uni-kiel.de':         { name: 'Christian-Albrechts-Universität zu Kiel', city: 'Kiel' },
  'uni-mainz.de':        { name: 'Johannes Gutenberg-Universität Mainz', city: 'Mainz' },
  'uni-marburg.de':      { name: 'Philipps-Universität Marburg', city: 'Marburg' },
  'uni-kassel.de':       { name: 'Universität Kassel', city: 'Kassel' },
  'uni-rostock.de':      { name: 'Universität Rostock', city: 'Rostock' },
  'uni-greifswald.de':   { name: 'Universität Greifswald', city: 'Greifswald' },
  'uni-halle.de':        { name: 'Martin-Luther-Universität Halle-Wittenberg', city: 'Halle' },
  'tu-dortmund.de':      { name: 'Technische Universität Dortmund', city: 'Dortmund' },
  'tu-hamburg.de':       { name: 'Technische Universität Hamburg', city: 'Hamburg' },
  'uni-bremen.de':       { name: 'Universität Bremen', city: 'Bremen' },
  'uni-paderborn.de':    { name: 'Universität Paderborn', city: 'Paderborn' },
  'uni-osnabrueck.de':   { name: 'Universität Osnabrück', city: 'Osnabrück' },
  'uni-oldenburg.de':    { name: 'Carl von Ossietzky Universität Oldenburg', city: 'Oldenburg' },
  'uni-passau.de':       { name: 'Universität Passau', city: 'Passau' },
  'uni-regensburg.de':   { name: 'Universität Regensburg', city: 'Regensburg' },
  'uni-bielefeld.de':    { name: 'Universität Bielefeld', city: 'Bielefeld' },
  'uni-siegen.de':       { name: 'Universität Siegen', city: 'Siegen' },
  'uni-trier.de':        { name: 'Universität Trier', city: 'Trier' },
  'uni-giessen.de':      { name: 'Justus-Liebig-Universität Gießen', city: 'Giessen' },
  'uni-magdeburg.de':    { name: 'Otto-von-Guericke-Universität Magdeburg', city: 'Magdeburg' },
  'tu-bs.de':            { name: 'Technische Universität Braunschweig', city: 'Braunschweig' },
  'tu-freiberg.de':      { name: 'TU Bergakademie Freiberg', city: 'Freiberg' },
  'rub.de':              { name: 'Ruhr-Universität Bochum', city: 'Bochum' },
  'uni-bochum.de':       { name: 'Ruhr-Universität Bochum', city: 'Bochum' },
  'hs-fulda.de':         { name: 'Hochschule Fulda', city: 'Fulda' },
  'th-koeln.de':         { name: 'TH Köln', city: 'Cologne' },
  'hochschule-rhein-waal.de': { name: 'Hochschule Rhein-Waal', city: 'Kleve' },
  'uni-weimar.de':       { name: 'Bauhaus-Universität Weimar', city: 'Weimar' },
  'b-tu.de':             { name: 'Brandenburgische Technische Universität Cottbus-Senftenberg', city: 'Cottbus' },
  'jacobs-university.de': { name: 'Constructor University (formerly Jacobs)', city: 'Bremen' },
  'constructor.university': { name: 'Constructor University', city: 'Bremen' },
  'daad.de':             { name: 'DAAD', city: '' },
  'studieren.de':        { name: '', city: '' },
};

/** Common German cities for detection */
export const GERMAN_CITIES = [
  'Berlin', 'Munich', 'München', 'Hamburg', 'Frankfurt', 'Cologne', 'Köln',
  'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dresden', 'Heidelberg', 'Freiburg',
  'Münster', 'Hannover', 'Nuremberg', 'Nürnberg', 'Bremen', 'Bochum',
  'Dortmund', 'Karlsruhe', 'Mannheim', 'Augsburg', 'Wiesbaden', 'Bielefeld',
  'Bonn', 'Aachen', 'Constance', 'Konstanz', 'Jena', 'Erfurt', 'Potsdam',
  'Kassel', 'Regensburg', 'Tübingen', 'Würzburg', 'Saarbrücken', 'Braunschweig',
  'Darmstadt', 'Göttingen', 'Marburg', 'Passau', 'Rostock', 'Magdeburg',
  'Kaiserslautern', 'Chemnitz', 'Ilmenau', 'Bayreuth', 'Erlangen',
  'Clausthal-Zellerfeld', 'Siegen', 'Paderborn', 'Osnabrück', 'Oldenburg',
  'Greifswald', 'Kiel', 'Lübeck', 'Giessen', 'Gießen', 'Mainz', 'Trier',
  'Wuppertal', 'Duisburg', 'Essen', 'Halle', 'Cottbus', 'Weimar', 'Fulda',
  'Kleve', 'Freiberg', 'Senftenberg', 'Landau',
];

/** Month name → 0-indexed month number (English + German) */
export const MONTH_MAP: Record<string, number> = {
  january: 0, february: 1, march: 2, april: 3, may: 4, june: 5,
  july: 6, august: 7, september: 8, october: 9, november: 10, december: 11,
  jan: 0, feb: 1, mar: 2, apr: 3, jun: 5, jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11,
  januar: 0, februar: 1, märz: 2, mai: 4, juni: 5,
  juli: 6, oktober: 9, dezember: 11,
};

/** Coordinates of major German cities for the map feature */
export const CITY_COORDINATES: Record<string, { lat: number; lng: number }> = {
  'Berlin':              { lat: 52.520, lng: 13.405 },
  'Munich':              { lat: 48.137, lng: 11.576 },
  'München':             { lat: 48.137, lng: 11.576 },
  'Hamburg':              { lat: 53.551, lng: 9.994 },
  'Frankfurt':           { lat: 50.110, lng: 8.682 },
  'Cologne':             { lat: 50.938, lng: 6.960 },
  'Köln':                { lat: 50.938, lng: 6.960 },
  'Stuttgart':           { lat: 48.776, lng: 9.183 },
  'Düsseldorf':          { lat: 51.228, lng: 6.773 },
  'Leipzig':             { lat: 51.340, lng: 12.375 },
  'Dresden':             { lat: 51.051, lng: 13.738 },
  'Heidelberg':          { lat: 49.399, lng: 8.672 },
  'Freiburg':            { lat: 47.999, lng: 7.842 },
  'Münster':             { lat: 51.962, lng: 7.626 },
  'Hannover':            { lat: 52.376, lng: 9.739 },
  'Nuremberg':           { lat: 49.452, lng: 11.077 },
  'Nürnberg':            { lat: 49.452, lng: 11.077 },
  'Bremen':              { lat: 53.075, lng: 8.807 },
  'Bochum':              { lat: 51.483, lng: 7.216 },
  'Dortmund':            { lat: 51.514, lng: 7.468 },
  'Karlsruhe':           { lat: 49.007, lng: 8.404 },
  'Mannheim':            { lat: 49.489, lng: 8.467 },
  'Augsburg':            { lat: 48.366, lng: 10.898 },
  'Bonn':                { lat: 50.735, lng: 7.100 },
  'Aachen':              { lat: 50.776, lng: 6.084 },
  'Constance':           { lat: 47.660, lng: 9.176 },
  'Konstanz':            { lat: 47.660, lng: 9.176 },
  'Jena':                { lat: 50.927, lng: 11.586 },
  'Erfurt':              { lat: 50.985, lng: 11.030 },
  'Potsdam':             { lat: 52.400, lng: 13.066 },
  'Tübingen':            { lat: 48.521, lng: 9.058 },
  'Würzburg':            { lat: 49.791, lng: 9.953 },
  'Saarbrücken':         { lat: 49.240, lng: 6.997 },
  'Braunschweig':        { lat: 52.269, lng: 10.522 },
  'Darmstadt':           { lat: 49.873, lng: 8.651 },
  'Göttingen':           { lat: 51.533, lng: 9.935 },
  'Erlangen':            { lat: 49.590, lng: 11.006 },
  'Kaiserslautern':      { lat: 49.443, lng: 7.769 },
  'Chemnitz':            { lat: 50.833, lng: 12.925 },
  'Ilmenau':             { lat: 50.684, lng: 10.914 },
  'Bayreuth':            { lat: 49.947, lng: 11.578 },
  'Clausthal-Zellerfeld': { lat: 51.803, lng: 10.339 },
  'Marburg':             { lat: 50.812, lng: 8.771 },
  'Rostock':             { lat: 54.092, lng: 12.099 },
  'Magdeburg':           { lat: 52.121, lng: 11.628 },
  'Kiel':                { lat: 54.323, lng: 10.123 },
  'Mainz':               { lat: 49.993, lng: 8.247 },
  'Trier':               { lat: 49.750, lng: 6.637 },
  'Passau':              { lat: 48.574, lng: 13.461 },
  'Regensburg':          { lat: 49.013, lng: 12.102 },
  'Giessen':             { lat: 50.583, lng: 8.678 },
  'Gießen':              { lat: 50.583, lng: 8.678 },
  'Siegen':              { lat: 50.874, lng: 8.024 },
  'Paderborn':           { lat: 51.719, lng: 8.757 },
  'Osnabrück':           { lat: 52.279, lng: 8.043 },
  'Oldenburg':           { lat: 53.144, lng: 8.214 },
  'Wuppertal':           { lat: 51.256, lng: 7.150 },
  'Duisburg':            { lat: 51.435, lng: 6.763 },
  'Essen':               { lat: 51.455, lng: 7.012 },
  'Weimar':              { lat: 50.980, lng: 11.330 },
  'Cottbus':             { lat: 51.756, lng: 14.332 },
  'Halle':               { lat: 51.497, lng: 11.970 },
  'Bielefeld':           { lat: 52.021, lng: 8.535 },
  'Lübeck':              { lat: 53.866, lng: 10.686 },
  'Greifswald':          { lat: 54.093, lng: 13.388 },
  'Fulda':               { lat: 50.555, lng: 9.679 },
  'Kleve':               { lat: 51.788, lng: 6.139 },
  'Freiberg':            { lat: 50.919, lng: 13.342 },
  'Landau':              { lat: 49.199, lng: 8.119 },
  'Senftenberg':         { lat: 51.525, lng: 14.000 },
};

/** User agents for rotation to avoid bot detection */
export const USER_AGENTS = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0',
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
];

/** Canonical degree mappings for normalization */
export const DEGREE_CANONICAL: Record<string, string> = {
  'master of science':  'Master of Science (M.Sc.)',
  'master of arts':     'Master of Arts (M.A.)',
  'master of engineering': 'Master of Engineering (M.Eng.)',
  'master of business administration': 'Master of Business Administration (MBA)',
  'master of laws':     'Master of Laws (LL.M.)',
  'master of education': 'Master of Education (M.Ed.)',
  'bachelor of science': 'Bachelor of Science (B.Sc.)',
  'bachelor of arts':   'Bachelor of Arts (B.A.)',
  'bachelor of engineering': 'Bachelor of Engineering (B.Eng.)',
  'm.sc.': 'Master of Science (M.Sc.)',
  'm.sc':  'Master of Science (M.Sc.)',
  'msc':   'Master of Science (M.Sc.)',
  'm.a.':  'Master of Arts (M.A.)',
  'm.a':   'Master of Arts (M.A.)',
  'ma':    'Master of Arts (M.A.)',
  'm.eng.': 'Master of Engineering (M.Eng.)',
  'm.eng': 'Master of Engineering (M.Eng.)',
  'mba':   'Master of Business Administration (MBA)',
  'llm':   'Master of Laws (LL.M.)',
  'll.m.': 'Master of Laws (LL.M.)',
  'm.ed.': 'Master of Education (M.Ed.)',
  'b.sc.': 'Bachelor of Science (B.Sc.)',
  'b.sc':  'Bachelor of Science (B.Sc.)',
  'bsc':   'Bachelor of Science (B.Sc.)',
  'b.a.':  'Bachelor of Arts (B.A.)',
  'b.a':   'Bachelor of Arts (B.A.)',
  'ba':    'Bachelor of Arts (B.A.)',
  'b.eng.': 'Bachelor of Engineering (B.Eng.)',
  'b.eng': 'Bachelor of Engineering (B.Eng.)',
  'phd':   'PhD',
  'doctorate': 'PhD',
  'diplom': 'Diplom',
  'staatsexamen': 'Staatsexamen',
  'magister': 'Magister',
};

/** Labels in various languages that indicate KV pair keys */
export const KV_KEY_PATTERNS = {
  courseName: /^(programme?|course|studiengang|study\s*programme?|degree\s*programme?|name\s*of\s*programme?)$/i,
  degree: /^(degree|abschluss|academic\s*degree|award|qualification|degree\s*type|abschlussgrad)$/i,
  language: /^(language|language\s*of\s*instruction|unterrichtssprache|sprache|teaching\s*language|medium\s*of\s*instruction|lehrsprache)$/i,
  duration: /^(duration|dauer|regelstudienzeit|standard\s*period|study\s*duration|period\s*of\s*study|length|studiendauer)$/i,
  fees: /^(tuition\s*fees?|fees?|studiengebühr|gebühr|kosten|cost|tuition|studienkosten)s?$/i,
  semesterFees: /semester\s*(?:fee|beitrag|contribution|gebühr)/i,
  deadline: /(?:application\s*)?deadline|bewerbungsfrist|application\s*period|bewerbungsschluss|application\s*deadline/i,
  startDate: /^(start|begin|start\s*date|beginn|studienbeginn|commencement|programme?\s*start)$/i,
  ects: /^(ects|credits?|credit\s*points?|leistungspunkte|cp|lp)$/i,
  location: /^(city|stadt|ort|location|standort|campus)$/i,
  requirements: /^(requirements?|admission\s*requirements?|entry\s*requirements?|prerequisites?|zugangsvoraussetzungen?|voraussetzungen?|eligibility)$/i,
};
